version: '3'
services:
    mysql:
        image: mysql:5.7.21
        container_name: mysql
        ports:
            - 3306:3306
        command:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
            - --default_storage_engine=InnoDB
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
            - --init-connect=SET NAMES utf8
            - --innodb_log_file_size=256M
            - --innodb_buffer_pool_size=3GB
            - --max_allowed_packet=20M
            - --bulk_insert_buffer_size=20M
            - --query_cache_size=32M
            - --skip-character-set-client-handshake
            - --skip-host-cache
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            TZ: "America/Sao_Paulo"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "textToSpeech"

volumes:
    mysql:
